name : daily_market_price_scraper

on:
  schedule:
    - cron: '0 6 * * *' # run at midnight UTC 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: setup python packages
        run: |
          python -m pip install --upgrade pip
          cd pricing_wizard
          pip install -r requirements.txt
          
      - name : run scraper method
        run: |
          cd pricing_wizard
          python -c 'from modules.market_price_scraper_v02_EU import market_price_scraper_v02_EU; market_price_scraper_v02_EU()'
          python -c 'from modules.market_price_scraper_v02_US import market_price_scraper_v02_US; market_price_scraper_v02_US()'
          
